name: Flutter CI/CD

on:
  push:
    branches:
      - main
      - publish_to_firebase
     
  pull_request:
    branches:
      - main
      - publish_to_firebase

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout My Code 
        uses: actions/checkout@v3

      # Setup Java 17
      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use the Eclipse Temurin distribution
          java-version: '17'

      # Install Flutter version 3.27.1 (adjusted to match your version)
      - name: Install Flutter Version 3.27.1
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # Use the required Flutter version

      # Install dependencies for Flutter
      - name: Install Dependencies
        run: flutter pub get

      # Run tests in the Flutter project
      - name: Run Our Test
        run: flutter test

      # Build the release APK
      - name: Build APK
        run: flutter build apk --release

      # Verify the APK file is created (for debugging purposes)
      - run: ls build/app/outputs/flutter-apk

      # Upload artifact to Firebase App Distribution
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APP_ID }}  # Firebase App ID from GitHub Secrets
          serviceCredentialsFileContent: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}  # Firebase Service Account Key (as GitHub Secret)
          groups: testers  # Firebase testers group (ensure this group exists in Firebase App Distribution)
          file: build/app/outputs/flutter-apk/app-release.apk  # Path to the built APK file
          
