name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the repository for checking out
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build APK for Android
      - name: Build APK for Android
        run: flutter build apk --release

      # Step 5: Install Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Step 6: Authenticate Firebase
      - name: Firebase Authentication
        run: firebase login:ci --token ${{ secrets.FIREBASE_TOKEN }}

      # Step 7: Deploy APK to Firebase App Distribution
      - name: Deploy APK to Firebase
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app 1:740071393518:android:0a9c518d74bd0987f14bff \
            --groups "testers" \
            --token ${{ secrets.FIREBASE_TOKEN }}
